/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from src to dst, ignoring pointers.
 * Note that only PWork are supposed to be pointers within a DWork structure
 * and that sub-structures are copied in one operation since they do not contain pointers.
 */
int OpalSnapshot_Copy_DWork(void * src, void * dst) {
   D_Work * pSrc = (D_Work*)src;
   D_Work * pDst = (D_Work*)dst;
   int size = 0, eltSize = 0;

   eltSize = sizeof(pSrc->UnitDelay2_DSTATE);
   memcpy(&pDst->UnitDelay2_DSTATE, &pSrc->UnitDelay2_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay2_DSTATE_i);
   memcpy(&pDst->UnitDelay2_DSTATE_i, &pSrc->UnitDelay2_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE, &pSrc->DiscreteTimeIntegrator_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_c);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_c, &pSrc->DiscreteTimeIntegrator_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9);
   memcpy(&pDst->MOV_segment9, &pSrc->MOV_segment9, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_b);
   memcpy(&pDst->MOV_segment9_b, &pSrc->MOV_segment9_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_l);
   memcpy(&pDst->MOV_segment9_l, &pSrc->MOV_segment9_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_i);
   memcpy(&pDst->MOV_segment9_i, &pSrc->MOV_segment9_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_n);
   memcpy(&pDst->MOV_segment9_n, &pSrc->MOV_segment9_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_nm);
   memcpy(&pDst->MOV_segment9_nm, &pSrc->MOV_segment9_nm, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_f);
   memcpy(&pDst->MOV_segment9_f, &pSrc->MOV_segment9_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_k);
   memcpy(&pDst->MOV_segment9_k, &pSrc->MOV_segment9_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_j);
   memcpy(&pDst->MOV_segment9_j, &pSrc->MOV_segment9_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_p);
   memcpy(&pDst->MOV_segment9_p, &pSrc->MOV_segment9_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_e);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_e, &pSrc->DiscreteTimeIntegrator_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE);
   memcpy(&pDst->Integ4_DSTATE, &pSrc->Integ4_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE);
   memcpy(&pDst->UnitDelay_DSTATE, &pSrc->UnitDelay_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_i);
   memcpy(&pDst->UnitDelay_DSTATE_i, &pSrc->UnitDelay_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_o);
   memcpy(&pDst->UnitDelay_DSTATE_o, &pSrc->UnitDelay_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE);
   memcpy(&pDst->DiscreteStateSpace_DSTATE, &pSrc->DiscreteStateSpace_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_n);
   memcpy(&pDst->UnitDelay_DSTATE_n, &pSrc->UnitDelay_DSTATE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_k);
   memcpy(&pDst->Integ4_DSTATE_k, &pSrc->Integ4_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE);
   memcpy(&pDst->UnitDelay1_DSTATE, &pSrc->UnitDelay1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_e);
   memcpy(&pDst->UnitDelay_DSTATE_e, &pSrc->UnitDelay_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_p);
   memcpy(&pDst->Integ4_DSTATE_p, &pSrc->Integ4_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_l);
   memcpy(&pDst->UnitDelay1_DSTATE_l, &pSrc->UnitDelay1_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_j);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_j, &pSrc->DiscreteTimeIntegrator_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_n);
   memcpy(&pDst->Integ4_DSTATE_n, &pSrc->Integ4_DSTATE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_c);
   memcpy(&pDst->UnitDelay_DSTATE_c, &pSrc->UnitDelay_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_d);
   memcpy(&pDst->UnitDelay_DSTATE_d, &pSrc->UnitDelay_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_g);
   memcpy(&pDst->UnitDelay_DSTATE_g, &pSrc->UnitDelay_DSTATE_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE_m);
   memcpy(&pDst->DiscreteStateSpace_DSTATE_m, &pSrc->DiscreteStateSpace_DSTATE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_o4);
   memcpy(&pDst->UnitDelay_DSTATE_o4, &pSrc->UnitDelay_DSTATE_o4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_i);
   memcpy(&pDst->Integ4_DSTATE_i, &pSrc->Integ4_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_d);
   memcpy(&pDst->UnitDelay1_DSTATE_d, &pSrc->UnitDelay1_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_j);
   memcpy(&pDst->UnitDelay_DSTATE_j, &pSrc->UnitDelay_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_o);
   memcpy(&pDst->Integ4_DSTATE_o, &pSrc->Integ4_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_m);
   memcpy(&pDst->UnitDelay1_DSTATE_m, &pSrc->UnitDelay1_DSTATE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_d);
   memcpy(&pDst->Integ4_DSTATE_d, &pSrc->Integ4_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_h);
   memcpy(&pDst->UnitDelay_DSTATE_h, &pSrc->UnitDelay_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_i);
   memcpy(&pDst->UnitDelay1_DSTATE_i, &pSrc->UnitDelay1_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_du);
   memcpy(&pDst->Integ4_DSTATE_du, &pSrc->Integ4_DSTATE_du, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_f);
   memcpy(&pDst->UnitDelay_DSTATE_f, &pSrc->UnitDelay_DSTATE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_g);
   memcpy(&pDst->UnitDelay1_DSTATE_g, &pSrc->UnitDelay1_DSTATE_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_m);
   memcpy(&pDst->Integ4_DSTATE_m, &pSrc->Integ4_DSTATE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_gd);
   memcpy(&pDst->UnitDelay_DSTATE_gd, &pSrc->UnitDelay_DSTATE_gd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_o);
   memcpy(&pDst->UnitDelay1_DSTATE_o, &pSrc->UnitDelay1_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_j);
   memcpy(&pDst->Integ4_DSTATE_j, &pSrc->Integ4_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_jj);
   memcpy(&pDst->UnitDelay_DSTATE_jj, &pSrc->UnitDelay_DSTATE_jj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_i4);
   memcpy(&pDst->UnitDelay1_DSTATE_i4, &pSrc->UnitDelay1_DSTATE_i4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_ko);
   memcpy(&pDst->Integ4_DSTATE_ko, &pSrc->Integ4_DSTATE_ko, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_eh);
   memcpy(&pDst->UnitDelay_DSTATE_eh, &pSrc->UnitDelay_DSTATE_eh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_b);
   memcpy(&pDst->UnitDelay1_DSTATE_b, &pSrc->UnitDelay1_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_dr);
   memcpy(&pDst->Integ4_DSTATE_dr, &pSrc->Integ4_DSTATE_dr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_ej);
   memcpy(&pDst->UnitDelay_DSTATE_ej, &pSrc->UnitDelay_DSTATE_ej, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_f);
   memcpy(&pDst->UnitDelay1_DSTATE_f, &pSrc->UnitDelay1_DSTATE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_h);
   memcpy(&pDst->Integ4_DSTATE_h, &pSrc->Integ4_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_eb);
   memcpy(&pDst->UnitDelay_DSTATE_eb, &pSrc->UnitDelay_DSTATE_eb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_od);
   memcpy(&pDst->UnitDelay1_DSTATE_od, &pSrc->UnitDelay1_DSTATE_od, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_p4);
   memcpy(&pDst->Integ4_DSTATE_p4, &pSrc->Integ4_DSTATE_p4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_eg);
   memcpy(&pDst->UnitDelay_DSTATE_eg, &pSrc->UnitDelay_DSTATE_eg, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_ix);
   memcpy(&pDst->UnitDelay1_DSTATE_ix, &pSrc->UnitDelay1_DSTATE_ix, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_e);
   memcpy(&pDst->Integ4_DSTATE_e, &pSrc->Integ4_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_np);
   memcpy(&pDst->UnitDelay_DSTATE_np, &pSrc->UnitDelay_DSTATE_np, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_ob);
   memcpy(&pDst->UnitDelay1_DSTATE_ob, &pSrc->UnitDelay1_DSTATE_ob, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_g);
   memcpy(&pDst->Integ4_DSTATE_g, &pSrc->Integ4_DSTATE_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_n4);
   memcpy(&pDst->UnitDelay_DSTATE_n4, &pSrc->UnitDelay_DSTATE_n4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_e);
   memcpy(&pDst->UnitDelay1_DSTATE_e, &pSrc->UnitDelay1_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_iq);
   memcpy(&pDst->Integ4_DSTATE_iq, &pSrc->Integ4_DSTATE_iq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_dl);
   memcpy(&pDst->UnitDelay_DSTATE_dl, &pSrc->UnitDelay_DSTATE_dl, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_c);
   memcpy(&pDst->UnitDelay1_DSTATE_c, &pSrc->UnitDelay1_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_b);
   memcpy(&pDst->Integ4_DSTATE_b, &pSrc->Integ4_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_p);
   memcpy(&pDst->UnitDelay_DSTATE_p, &pSrc->UnitDelay_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_gi);
   memcpy(&pDst->UnitDelay1_DSTATE_gi, &pSrc->UnitDelay1_DSTATE_gi, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_jx);
   memcpy(&pDst->Integ4_DSTATE_jx, &pSrc->Integ4_DSTATE_jx, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_ie);
   memcpy(&pDst->UnitDelay_DSTATE_ie, &pSrc->UnitDelay_DSTATE_ie, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_k);
   memcpy(&pDst->UnitDelay1_DSTATE_k, &pSrc->UnitDelay1_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_bn);
   memcpy(&pDst->Integ4_DSTATE_bn, &pSrc->Integ4_DSTATE_bn, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_dh);
   memcpy(&pDst->UnitDelay_DSTATE_dh, &pSrc->UnitDelay_DSTATE_dh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_o0);
   memcpy(&pDst->UnitDelay1_DSTATE_o0, &pSrc->UnitDelay1_DSTATE_o0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_p1);
   memcpy(&pDst->Integ4_DSTATE_p1, &pSrc->Integ4_DSTATE_p1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_cv);
   memcpy(&pDst->UnitDelay_DSTATE_cv, &pSrc->UnitDelay_DSTATE_cv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_j);
   memcpy(&pDst->UnitDelay1_DSTATE_j, &pSrc->UnitDelay1_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_f);
   memcpy(&pDst->Integ4_DSTATE_f, &pSrc->Integ4_DSTATE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_g5);
   memcpy(&pDst->UnitDelay_DSTATE_g5, &pSrc->UnitDelay_DSTATE_g5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_gj);
   memcpy(&pDst->UnitDelay1_DSTATE_gj, &pSrc->UnitDelay1_DSTATE_gj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_o0);
   memcpy(&pDst->Integ4_DSTATE_o0, &pSrc->Integ4_DSTATE_o0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_a);
   memcpy(&pDst->UnitDelay_DSTATE_a, &pSrc->UnitDelay_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_p);
   memcpy(&pDst->UnitDelay1_DSTATE_p, &pSrc->UnitDelay1_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_p5);
   memcpy(&pDst->Integ4_DSTATE_p5, &pSrc->Integ4_DSTATE_p5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_j4);
   memcpy(&pDst->UnitDelay_DSTATE_j4, &pSrc->UnitDelay_DSTATE_j4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_ow);
   memcpy(&pDst->UnitDelay1_DSTATE_ow, &pSrc->UnitDelay1_DSTATE_ow, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_a);
   memcpy(&pDst->Integ4_DSTATE_a, &pSrc->Integ4_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_b);
   memcpy(&pDst->UnitDelay_DSTATE_b, &pSrc->UnitDelay_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_h);
   memcpy(&pDst->UnitDelay1_DSTATE_h, &pSrc->UnitDelay1_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_ip);
   memcpy(&pDst->Integ4_DSTATE_ip, &pSrc->Integ4_DSTATE_ip, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_cx);
   memcpy(&pDst->UnitDelay_DSTATE_cx, &pSrc->UnitDelay_DSTATE_cx, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_c0);
   memcpy(&pDst->UnitDelay1_DSTATE_c0, &pSrc->UnitDelay1_DSTATE_c0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_g0);
   memcpy(&pDst->Integ4_DSTATE_g0, &pSrc->Integ4_DSTATE_g0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_m);
   memcpy(&pDst->UnitDelay_DSTATE_m, &pSrc->UnitDelay_DSTATE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_cw);
   memcpy(&pDst->UnitDelay1_DSTATE_cw, &pSrc->UnitDelay1_DSTATE_cw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_md);
   memcpy(&pDst->Integ4_DSTATE_md, &pSrc->Integ4_DSTATE_md, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_ca);
   memcpy(&pDst->UnitDelay_DSTATE_ca, &pSrc->UnitDelay_DSTATE_ca, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_oe);
   memcpy(&pDst->UnitDelay1_DSTATE_oe, &pSrc->UnitDelay1_DSTATE_oe, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_gc);
   memcpy(&pDst->Integ4_DSTATE_gc, &pSrc->Integ4_DSTATE_gc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_pm);
   memcpy(&pDst->UnitDelay_DSTATE_pm, &pSrc->UnitDelay_DSTATE_pm, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_ld);
   memcpy(&pDst->UnitDelay1_DSTATE_ld, &pSrc->UnitDelay1_DSTATE_ld, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_hu);
   memcpy(&pDst->Integ4_DSTATE_hu, &pSrc->Integ4_DSTATE_hu, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_gg);
   memcpy(&pDst->UnitDelay_DSTATE_gg, &pSrc->UnitDelay_DSTATE_gg, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_oq);
   memcpy(&pDst->UnitDelay1_DSTATE_oq, &pSrc->UnitDelay1_DSTATE_oq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_l);
   memcpy(&pDst->Integ4_DSTATE_l, &pSrc->Integ4_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_hj);
   memcpy(&pDst->UnitDelay_DSTATE_hj, &pSrc->UnitDelay_DSTATE_hj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_j1);
   memcpy(&pDst->UnitDelay1_DSTATE_j1, &pSrc->UnitDelay1_DSTATE_j1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_fk);
   memcpy(&pDst->Integ4_DSTATE_fk, &pSrc->Integ4_DSTATE_fk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_ag);
   memcpy(&pDst->UnitDelay_DSTATE_ag, &pSrc->UnitDelay_DSTATE_ag, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_a);
   memcpy(&pDst->UnitDelay1_DSTATE_a, &pSrc->UnitDelay1_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_fv);
   memcpy(&pDst->Integ4_DSTATE_fv, &pSrc->Integ4_DSTATE_fv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_bu);
   memcpy(&pDst->UnitDelay_DSTATE_bu, &pSrc->UnitDelay_DSTATE_bu, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_cq);
   memcpy(&pDst->UnitDelay1_DSTATE_cq, &pSrc->UnitDelay1_DSTATE_cq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_fd);
   memcpy(&pDst->Integ4_DSTATE_fd, &pSrc->Integ4_DSTATE_fd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_e1);
   memcpy(&pDst->UnitDelay_DSTATE_e1, &pSrc->UnitDelay_DSTATE_e1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_fp);
   memcpy(&pDst->UnitDelay1_DSTATE_fp, &pSrc->UnitDelay1_DSTATE_fp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_c);
   memcpy(&pDst->Integ4_DSTATE_c, &pSrc->Integ4_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_k);
   memcpy(&pDst->UnitDelay_DSTATE_k, &pSrc->UnitDelay_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_ln);
   memcpy(&pDst->UnitDelay1_DSTATE_ln, &pSrc->UnitDelay1_DSTATE_ln, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_ph);
   memcpy(&pDst->Integ4_DSTATE_ph, &pSrc->Integ4_DSTATE_ph, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_mw);
   memcpy(&pDst->UnitDelay_DSTATE_mw, &pSrc->UnitDelay_DSTATE_mw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_gp);
   memcpy(&pDst->UnitDelay1_DSTATE_gp, &pSrc->UnitDelay1_DSTATE_gp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_ae);
   memcpy(&pDst->Integ4_DSTATE_ae, &pSrc->Integ4_DSTATE_ae, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_l);
   memcpy(&pDst->UnitDelay_DSTATE_l, &pSrc->UnitDelay_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_da);
   memcpy(&pDst->UnitDelay1_DSTATE_da, &pSrc->UnitDelay1_DSTATE_da, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_hv);
   memcpy(&pDst->Integ4_DSTATE_hv, &pSrc->Integ4_DSTATE_hv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_gz);
   memcpy(&pDst->UnitDelay_DSTATE_gz, &pSrc->UnitDelay_DSTATE_gz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_ov);
   memcpy(&pDst->UnitDelay1_DSTATE_ov, &pSrc->UnitDelay1_DSTATE_ov, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_mz);
   memcpy(&pDst->Integ4_DSTATE_mz, &pSrc->Integ4_DSTATE_mz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_h5);
   memcpy(&pDst->UnitDelay_DSTATE_h5, &pSrc->UnitDelay_DSTATE_h5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_f5);
   memcpy(&pDst->UnitDelay1_DSTATE_f5, &pSrc->UnitDelay1_DSTATE_f5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_gg);
   memcpy(&pDst->Integ4_DSTATE_gg, &pSrc->Integ4_DSTATE_gg, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_hh);
   memcpy(&pDst->UnitDelay_DSTATE_hh, &pSrc->UnitDelay_DSTATE_hh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_h1);
   memcpy(&pDst->UnitDelay1_DSTATE_h1, &pSrc->UnitDelay1_DSTATE_h1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_gv);
   memcpy(&pDst->Integ4_DSTATE_gv, &pSrc->Integ4_DSTATE_gv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_fz);
   memcpy(&pDst->UnitDelay_DSTATE_fz, &pSrc->UnitDelay_DSTATE_fz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_oi);
   memcpy(&pDst->UnitDelay1_DSTATE_oi, &pSrc->UnitDelay1_DSTATE_oi, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_pj);
   memcpy(&pDst->Integ4_DSTATE_pj, &pSrc->Integ4_DSTATE_pj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_ff);
   memcpy(&pDst->UnitDelay_DSTATE_ff, &pSrc->UnitDelay_DSTATE_ff, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_jq);
   memcpy(&pDst->UnitDelay1_DSTATE_jq, &pSrc->UnitDelay1_DSTATE_jq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_ol);
   memcpy(&pDst->Integ4_DSTATE_ol, &pSrc->Integ4_DSTATE_ol, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_gb);
   memcpy(&pDst->UnitDelay_DSTATE_gb, &pSrc->UnitDelay_DSTATE_gb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_bj);
   memcpy(&pDst->UnitDelay1_DSTATE_bj, &pSrc->UnitDelay1_DSTATE_bj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_hx);
   memcpy(&pDst->Integ4_DSTATE_hx, &pSrc->Integ4_DSTATE_hx, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_ic);
   memcpy(&pDst->UnitDelay_DSTATE_ic, &pSrc->UnitDelay_DSTATE_ic, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_b0);
   memcpy(&pDst->UnitDelay1_DSTATE_b0, &pSrc->UnitDelay1_DSTATE_b0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_ap);
   memcpy(&pDst->Integ4_DSTATE_ap, &pSrc->Integ4_DSTATE_ap, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_mws);
   memcpy(&pDst->UnitDelay_DSTATE_mws, &pSrc->UnitDelay_DSTATE_mws, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_pw);
   memcpy(&pDst->UnitDelay1_DSTATE_pw, &pSrc->UnitDelay1_DSTATE_pw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_PreviousInput);
   memcpy(&pDst->SFunction_PreviousInput, &pSrc->SFunction_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin);
   memcpy(&pDst->lastSin, &pSrc->lastSin, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos);
   memcpy(&pDst->lastCos, &pSrc->lastCos, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_e);
   memcpy(&pDst->lastSin_e, &pSrc->lastSin_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_d);
   memcpy(&pDst->lastCos_d, &pSrc->lastCos_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_f);
   memcpy(&pDst->lastSin_f, &pSrc->lastSin_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_j);
   memcpy(&pDst->lastCos_j, &pSrc->lastCos_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput);
   memcpy(&pDst->Memory_PreviousInput, &pSrc->Memory_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_k);
   memcpy(&pDst->Memory_PreviousInput_k, &pSrc->Memory_PreviousInput_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_n);
   memcpy(&pDst->Memory_PreviousInput_n, &pSrc->Memory_PreviousInput_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Initial_FirstOutputTime);
   memcpy(&pDst->Initial_FirstOutputTime, &pSrc->Initial_FirstOutputTime, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_c);
   memcpy(&pDst->Memory_PreviousInput_c, &pSrc->Memory_PreviousInput_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PrevY);
   memcpy(&pDst->PrevY, &pSrc->PrevY, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastMajorTime);
   memcpy(&pDst->LastMajorTime, &pSrc->LastMajorTime, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Initial_FirstOutputTime_n);
   memcpy(&pDst->Initial_FirstOutputTime_n, &pSrc->Initial_FirstOutputTime_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_d);
   memcpy(&pDst->Memory_PreviousInput_d, &pSrc->Memory_PreviousInput_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PrevY_c);
   memcpy(&pDst->PrevY_c, &pSrc->PrevY_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastMajorTime_e);
   memcpy(&pDst->LastMajorTime_e, &pSrc->LastMajorTime_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Initial_FirstOutputTime_f);
   memcpy(&pDst->Initial_FirstOutputTime_f, &pSrc->Initial_FirstOutputTime_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_a);
   memcpy(&pDst->Memory_PreviousInput_a, &pSrc->Memory_PreviousInput_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PrevY_p);
   memcpy(&pDst->PrevY_p, &pSrc->PrevY_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastMajorTime_g);
   memcpy(&pDst->LastMajorTime_g, &pSrc->LastMajorTime_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_g);
   memcpy(&pDst->lastSin_g, &pSrc->lastSin_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_c);
   memcpy(&pDst->lastCos_c, &pSrc->lastCos_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_n);
   memcpy(&pDst->lastSin_n, &pSrc->lastSin_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_jw);
   memcpy(&pDst->lastCos_jw, &pSrc->lastCos_jw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_o);
   memcpy(&pDst->lastSin_o, &pSrc->lastSin_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_h);
   memcpy(&pDst->lastCos_h, &pSrc->lastCos_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_k);
   memcpy(&pDst->lastSin_k, &pSrc->lastSin_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_m);
   memcpy(&pDst->lastCos_m, &pSrc->lastCos_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_m);
   memcpy(&pDst->lastSin_m, &pSrc->lastSin_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_a);
   memcpy(&pDst->lastCos_a, &pSrc->lastCos_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_gf);
   memcpy(&pDst->lastSin_gf, &pSrc->lastSin_gf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_i);
   memcpy(&pDst->lastCos_i, &pSrc->lastCos_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_d);
   memcpy(&pDst->lastSin_d, &pSrc->lastSin_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_g);
   memcpy(&pDst->lastCos_g, &pSrc->lastCos_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_b);
   memcpy(&pDst->lastSin_b, &pSrc->lastSin_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_e);
   memcpy(&pDst->lastCos_e, &pSrc->lastCos_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_mn);
   memcpy(&pDst->lastSin_mn, &pSrc->lastSin_mn, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_ds);
   memcpy(&pDst->lastCos_ds, &pSrc->lastCos_ds, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_bc);
   memcpy(&pDst->lastSin_bc, &pSrc->lastSin_bc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_jr);
   memcpy(&pDst->lastCos_jr, &pSrc->lastCos_jr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_j);
   memcpy(&pDst->lastSin_j, &pSrc->lastSin_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_b);
   memcpy(&pDst->lastCos_b, &pSrc->lastCos_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_dn);
   memcpy(&pDst->lastSin_dn, &pSrc->lastSin_dn, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_cb);
   memcpy(&pDst->lastCos_cb, &pSrc->lastCos_cb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_n2);
   memcpy(&pDst->lastSin_n2, &pSrc->lastSin_n2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_e3);
   memcpy(&pDst->lastCos_e3, &pSrc->lastCos_e3, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_p);
   memcpy(&pDst->lastSin_p, &pSrc->lastSin_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_n);
   memcpy(&pDst->lastCos_n, &pSrc->lastCos_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_i);
   memcpy(&pDst->lastSin_i, &pSrc->lastSin_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_o);
   memcpy(&pDst->lastCos_o, &pSrc->lastCos_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_l);
   memcpy(&pDst->lastSin_l, &pSrc->lastSin_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_l);
   memcpy(&pDst->lastCos_l, &pSrc->lastCos_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_jr);
   memcpy(&pDst->lastSin_jr, &pSrc->lastSin_jr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_ja);
   memcpy(&pDst->lastCos_ja, &pSrc->lastCos_ja, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_jh);
   memcpy(&pDst->lastSin_jh, &pSrc->lastSin_jh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_jb);
   memcpy(&pDst->lastCos_jb, &pSrc->lastCos_jb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_kx);
   memcpy(&pDst->lastSin_kx, &pSrc->lastSin_kx, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_k);
   memcpy(&pDst->lastCos_k, &pSrc->lastCos_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_fu);
   memcpy(&pDst->lastSin_fu, &pSrc->lastSin_fu, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_ky);
   memcpy(&pDst->lastCos_ky, &pSrc->lastCos_ky, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_pd);
   memcpy(&pDst->lastSin_pd, &pSrc->lastSin_pd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_f);
   memcpy(&pDst->lastCos_f, &pSrc->lastCos_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_oq);
   memcpy(&pDst->lastSin_oq, &pSrc->lastSin_oq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_bo);
   memcpy(&pDst->lastCos_bo, &pSrc->lastCos_bo, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_dh);
   memcpy(&pDst->lastSin_dh, &pSrc->lastSin_dh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_bk);
   memcpy(&pDst->lastCos_bk, &pSrc->lastCos_bk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_et);
   memcpy(&pDst->lastSin_et, &pSrc->lastSin_et, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_kk);
   memcpy(&pDst->lastCos_kk, &pSrc->lastCos_kk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_b4);
   memcpy(&pDst->lastSin_b4, &pSrc->lastSin_b4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_ie);
   memcpy(&pDst->lastCos_ie, &pSrc->lastCos_ie, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_gs);
   memcpy(&pDst->lastSin_gs, &pSrc->lastSin_gs, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_oc);
   memcpy(&pDst->lastCos_oc, &pSrc->lastCos_oc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_RWORK);
   memcpy(&pDst->TransportDelay_RWORK, &pSrc->TransportDelay_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_RWORK_d);
   memcpy(&pDst->TransportDelay_RWORK_d, &pSrc->TransportDelay_RWORK_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_RWORK_c);
   memcpy(&pDst->TransportDelay_RWORK_c, &pSrc->TransportDelay_RWORK_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->VariableTransportDelay_RWORK);
   memcpy(&pDst->VariableTransportDelay_RWORK, &pSrc->VariableTransportDelay_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->VariableTransportDelay_RWORK_a);
   memcpy(&pDst->VariableTransportDelay_RWORK_a, &pSrc->VariableTransportDelay_RWORK_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->VariableTransportDelay_RWORK_e);
   memcpy(&pDst->VariableTransportDelay_RWORK_e, &pSrc->VariableTransportDelay_RWORK_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK);
   memcpy(&pDst->SFunction_RWORK, &pSrc->SFunction_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_m);
   memcpy(&pDst->SFunction_RWORK_m, &pSrc->SFunction_RWORK_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_k);
   memcpy(&pDst->SFunction_RWORK_k, &pSrc->SFunction_RWORK_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_p);
   memcpy(&pDst->SFunction_RWORK_p, &pSrc->SFunction_RWORK_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_d);
   memcpy(&pDst->SFunction_RWORK_d, &pSrc->SFunction_RWORK_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_e);
   memcpy(&pDst->SFunction_RWORK_e, &pSrc->SFunction_RWORK_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_a);
   memcpy(&pDst->SFunction_RWORK_a, &pSrc->SFunction_RWORK_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_n);
   memcpy(&pDst->SFunction_RWORK_n, &pSrc->SFunction_RWORK_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_j);
   memcpy(&pDst->SFunction_RWORK_j, &pSrc->SFunction_RWORK_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_b);
   memcpy(&pDst->SFunction_RWORK_b, &pSrc->SFunction_RWORK_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_n5);
   memcpy(&pDst->SFunction_RWORK_n5, &pSrc->SFunction_RWORK_n5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_pb);
   memcpy(&pDst->SFunction_RWORK_pb, &pSrc->SFunction_RWORK_pb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_l);
   memcpy(&pDst->SFunction_RWORK_l, &pSrc->SFunction_RWORK_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_lv);
   memcpy(&pDst->SFunction_RWORK_lv, &pSrc->SFunction_RWORK_lv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_px);
   memcpy(&pDst->SFunction_RWORK_px, &pSrc->SFunction_RWORK_px, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_f);
   memcpy(&pDst->SFunction_RWORK_f, &pSrc->SFunction_RWORK_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_ex);
   memcpy(&pDst->SFunction_RWORK_ex, &pSrc->SFunction_RWORK_ex, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_o);
   memcpy(&pDst->SFunction_RWORK_o, &pSrc->SFunction_RWORK_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_bn);
   memcpy(&pDst->SFunction_RWORK_bn, &pSrc->SFunction_RWORK_bn, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_h);
   memcpy(&pDst->SFunction_RWORK_h, &pSrc->SFunction_RWORK_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_em);
   memcpy(&pDst->SFunction_RWORK_em, &pSrc->SFunction_RWORK_em, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_pj);
   memcpy(&pDst->SFunction_RWORK_pj, &pSrc->SFunction_RWORK_pj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_np);
   memcpy(&pDst->SFunction_RWORK_np, &pSrc->SFunction_RWORK_np, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_g);
   memcpy(&pDst->SFunction_RWORK_g, &pSrc->SFunction_RWORK_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_kq);
   memcpy(&pDst->SFunction_RWORK_kq, &pSrc->SFunction_RWORK_kq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_pja);
   memcpy(&pDst->SFunction_RWORK_pja, &pSrc->SFunction_RWORK_pja, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_or);
   memcpy(&pDst->SFunction_RWORK_or, &pSrc->SFunction_RWORK_or, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_ot);
   memcpy(&pDst->SFunction_RWORK_ot, &pSrc->SFunction_RWORK_ot, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_k1);
   memcpy(&pDst->SFunction_RWORK_k1, &pSrc->SFunction_RWORK_k1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_k1v);
   memcpy(&pDst->SFunction_RWORK_k1v, &pSrc->SFunction_RWORK_k1v, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_e0);
   memcpy(&pDst->SFunction_RWORK_e0, &pSrc->SFunction_RWORK_e0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_hz);
   memcpy(&pDst->SFunction_RWORK_hz, &pSrc->SFunction_RWORK_hz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_e3);
   memcpy(&pDst->SFunction_RWORK_e3, &pSrc->SFunction_RWORK_e3, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_jv);
   memcpy(&pDst->SFunction_RWORK_jv, &pSrc->SFunction_RWORK_jv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_kg);
   memcpy(&pDst->SFunction_RWORK_kg, &pSrc->SFunction_RWORK_kg, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_ll);
   memcpy(&pDst->SFunction_RWORK_ll, &pSrc->SFunction_RWORK_ll, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_dt);
   memcpy(&pDst->SFunction_RWORK_dt, &pSrc->SFunction_RWORK_dt, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_al);
   memcpy(&pDst->SFunction_RWORK_al, &pSrc->SFunction_RWORK_al, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_ln);
   memcpy(&pDst->SFunction_RWORK_ln, &pSrc->SFunction_RWORK_ln, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_pp);
   memcpy(&pDst->SFunction_RWORK_pp, &pSrc->SFunction_RWORK_pp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_l3);
   memcpy(&pDst->SFunction_RWORK_l3, &pSrc->SFunction_RWORK_l3, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_jm);
   memcpy(&pDst->SFunction_RWORK_jm, &pSrc->SFunction_RWORK_jm, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_ho);
   memcpy(&pDst->SFunction_RWORK_ho, &pSrc->SFunction_RWORK_ho, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable);
   memcpy(&pDst->systemEnable, &pSrc->systemEnable, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_c);
   memcpy(&pDst->systemEnable_c, &pSrc->systemEnable_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_e);
   memcpy(&pDst->systemEnable_e, &pSrc->systemEnable_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->clockTickCounter);
   memcpy(&pDst->clockTickCounter, &pSrc->clockTickCounter, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_eh);
   memcpy(&pDst->systemEnable_eh, &pSrc->systemEnable_eh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_ek);
   memcpy(&pDst->systemEnable_ek, &pSrc->systemEnable_ek, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_h);
   memcpy(&pDst->systemEnable_h, &pSrc->systemEnable_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_n);
   memcpy(&pDst->systemEnable_n, &pSrc->systemEnable_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_f);
   memcpy(&pDst->systemEnable_f, &pSrc->systemEnable_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_a);
   memcpy(&pDst->systemEnable_a, &pSrc->systemEnable_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_c0);
   memcpy(&pDst->systemEnable_c0, &pSrc->systemEnable_c0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_er);
   memcpy(&pDst->systemEnable_er, &pSrc->systemEnable_er, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_l);
   memcpy(&pDst->systemEnable_l, &pSrc->systemEnable_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_cc);
   memcpy(&pDst->systemEnable_cc, &pSrc->systemEnable_cc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_p);
   memcpy(&pDst->systemEnable_p, &pSrc->systemEnable_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_av);
   memcpy(&pDst->systemEnable_av, &pSrc->systemEnable_av, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_i);
   memcpy(&pDst->systemEnable_i, &pSrc->systemEnable_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_c00);
   memcpy(&pDst->systemEnable_c00, &pSrc->systemEnable_c00, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_it);
   memcpy(&pDst->systemEnable_it, &pSrc->systemEnable_it, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_n3);
   memcpy(&pDst->systemEnable_n3, &pSrc->systemEnable_n3, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_iu);
   memcpy(&pDst->systemEnable_iu, &pSrc->systemEnable_iu, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_d);
   memcpy(&pDst->systemEnable_d, &pSrc->systemEnable_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_h4);
   memcpy(&pDst->systemEnable_h4, &pSrc->systemEnable_h4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_au);
   memcpy(&pDst->systemEnable_au, &pSrc->systemEnable_au, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_g);
   memcpy(&pDst->systemEnable_g, &pSrc->systemEnable_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_m);
   memcpy(&pDst->systemEnable_m, &pSrc->systemEnable_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_dr);
   memcpy(&pDst->systemEnable_dr, &pSrc->systemEnable_dr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_o);
   memcpy(&pDst->systemEnable_o, &pSrc->systemEnable_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_az);
   memcpy(&pDst->systemEnable_az, &pSrc->systemEnable_az, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_cp);
   memcpy(&pDst->systemEnable_cp, &pSrc->systemEnable_cp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_IWORK);
   memcpy(&pDst->TransportDelay_IWORK, &pSrc->TransportDelay_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_IWORK_p);
   memcpy(&pDst->TransportDelay_IWORK_p, &pSrc->TransportDelay_IWORK_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_IWORK_n);
   memcpy(&pDst->TransportDelay_IWORK_n, &pSrc->TransportDelay_IWORK_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK);
   memcpy(&pDst->SFunction_IWORK, &pSrc->SFunction_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_IWORK);
   memcpy(&pDst->Integrator_IWORK, &pSrc->Integrator_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->VariableTransportDelay_IWORK);
   memcpy(&pDst->VariableTransportDelay_IWORK, &pSrc->VariableTransportDelay_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_IWORK_a);
   memcpy(&pDst->Integrator_IWORK_a, &pSrc->Integrator_IWORK_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->VariableTransportDelay_IWORK_k);
   memcpy(&pDst->VariableTransportDelay_IWORK_k, &pSrc->VariableTransportDelay_IWORK_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_IWORK_m);
   memcpy(&pDst->Integrator_IWORK_m, &pSrc->Integrator_IWORK_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->VariableTransportDelay_IWORK_a);
   memcpy(&pDst->VariableTransportDelay_IWORK_a, &pSrc->VariableTransportDelay_IWORK_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_f);
   memcpy(&pDst->SFunction_IWORK_f, &pSrc->SFunction_IWORK_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_fb);
   memcpy(&pDst->SFunction_IWORK_fb, &pSrc->SFunction_IWORK_fb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_p);
   memcpy(&pDst->SFunction_IWORK_p, &pSrc->SFunction_IWORK_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_i);
   memcpy(&pDst->SFunction_IWORK_i, &pSrc->SFunction_IWORK_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_o);
   memcpy(&pDst->SFunction_IWORK_o, &pSrc->SFunction_IWORK_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_d);
   memcpy(&pDst->SFunction_IWORK_d, &pSrc->SFunction_IWORK_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->OpCtrlML605EX1_IWORK);
   memcpy(&pDst->OpCtrlML605EX1_IWORK, &pSrc->OpCtrlML605EX1_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_h);
   memcpy(&pDst->SFunction_IWORK_h, &pSrc->SFunction_IWORK_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_e);
   memcpy(&pDst->SFunction_IWORK_e, &pSrc->SFunction_IWORK_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_a);
   memcpy(&pDst->SFunction_IWORK_a, &pSrc->SFunction_IWORK_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_g);
   memcpy(&pDst->SFunction_IWORK_g, &pSrc->SFunction_IWORK_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_j);
   memcpy(&pDst->SFunction_IWORK_j, &pSrc->SFunction_IWORK_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_a0);
   memcpy(&pDst->SFunction_IWORK_a0, &pSrc->SFunction_IWORK_a0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_au);
   memcpy(&pDst->SFunction_IWORK_au, &pSrc->SFunction_IWORK_au, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_l);
   memcpy(&pDst->SFunction_IWORK_l, &pSrc->SFunction_IWORK_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_p4);
   memcpy(&pDst->SFunction_IWORK_p4, &pSrc->SFunction_IWORK_p4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_f3);
   memcpy(&pDst->SFunction_IWORK_f3, &pSrc->SFunction_IWORK_f3, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_m);
   memcpy(&pDst->SFunction_IWORK_m, &pSrc->SFunction_IWORK_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_c);
   memcpy(&pDst->SFunction_IWORK_c, &pSrc->SFunction_IWORK_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_j0);
   memcpy(&pDst->SFunction_IWORK_j0, &pSrc->SFunction_IWORK_j0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_ov);
   memcpy(&pDst->SFunction_IWORK_ov, &pSrc->SFunction_IWORK_ov, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_hi);
   memcpy(&pDst->SFunction_IWORK_hi, &pSrc->SFunction_IWORK_hi, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_o0);
   memcpy(&pDst->SFunction_IWORK_o0, &pSrc->SFunction_IWORK_o0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_f1);
   memcpy(&pDst->SFunction_IWORK_f1, &pSrc->SFunction_IWORK_f1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_gv);
   memcpy(&pDst->SFunction_IWORK_gv, &pSrc->SFunction_IWORK_gv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_ov4);
   memcpy(&pDst->SFunction_IWORK_ov4, &pSrc->SFunction_IWORK_ov4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_k);
   memcpy(&pDst->SFunction_IWORK_k, &pSrc->SFunction_IWORK_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_gq);
   memcpy(&pDst->SFunction_IWORK_gq, &pSrc->SFunction_IWORK_gq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_hs);
   memcpy(&pDst->SFunction_IWORK_hs, &pSrc->SFunction_IWORK_hs, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_pq);
   memcpy(&pDst->SFunction_IWORK_pq, &pSrc->SFunction_IWORK_pq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_ce);
   memcpy(&pDst->SFunction_IWORK_ce, &pSrc->SFunction_IWORK_ce, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_ku);
   memcpy(&pDst->SFunction_IWORK_ku, &pSrc->SFunction_IWORK_ku, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_pr);
   memcpy(&pDst->SFunction_IWORK_pr, &pSrc->SFunction_IWORK_pr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_n);
   memcpy(&pDst->SFunction_IWORK_n, &pSrc->SFunction_IWORK_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_lf);
   memcpy(&pDst->SFunction_IWORK_lf, &pSrc->SFunction_IWORK_lf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_pv);
   memcpy(&pDst->SFunction_IWORK_pv, &pSrc->SFunction_IWORK_pv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_f4);
   memcpy(&pDst->SFunction_IWORK_f4, &pSrc->SFunction_IWORK_f4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_cw);
   memcpy(&pDst->SFunction_IWORK_cw, &pSrc->SFunction_IWORK_cw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_a4);
   memcpy(&pDst->SFunction_IWORK_a4, &pSrc->SFunction_IWORK_a4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_b);
   memcpy(&pDst->SFunction_IWORK_b, &pSrc->SFunction_IWORK_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_pd);
   memcpy(&pDst->SFunction_IWORK_pd, &pSrc->SFunction_IWORK_pd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_im);
   memcpy(&pDst->SFunction_IWORK_im, &pSrc->SFunction_IWORK_im, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_ez);
   memcpy(&pDst->SFunction_IWORK_ez, &pSrc->SFunction_IWORK_ez, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_dn);
   memcpy(&pDst->SFunction_IWORK_dn, &pSrc->SFunction_IWORK_dn, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_dz);
   memcpy(&pDst->SFunction_IWORK_dz, &pSrc->SFunction_IWORK_dz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_pj);
   memcpy(&pDst->SFunction_IWORK_pj, &pSrc->SFunction_IWORK_pj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_cm);
   memcpy(&pDst->SFunction_IWORK_cm, &pSrc->SFunction_IWORK_cm, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE, &pSrc->Integ4_SYSTEM_ENABLE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_l);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_l, &pSrc->Integ4_SYSTEM_ENABLE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_i);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_i, &pSrc->Integ4_SYSTEM_ENABLE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_o);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_o, &pSrc->Integ4_SYSTEM_ENABLE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_f);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_f, &pSrc->Integ4_SYSTEM_ENABLE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_d);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_d, &pSrc->Integ4_SYSTEM_ENABLE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_lw);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_lw, &pSrc->Integ4_SYSTEM_ENABLE_lw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_j);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_j, &pSrc->Integ4_SYSTEM_ENABLE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_n);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_n, &pSrc->Integ4_SYSTEM_ENABLE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_a);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_a, &pSrc->Integ4_SYSTEM_ENABLE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_e);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_e, &pSrc->Integ4_SYSTEM_ENABLE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_b);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_b, &pSrc->Integ4_SYSTEM_ENABLE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_m);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_m, &pSrc->Integ4_SYSTEM_ENABLE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_o4);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_o4, &pSrc->Integ4_SYSTEM_ENABLE_o4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_oq);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_oq, &pSrc->Integ4_SYSTEM_ENABLE_oq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_h);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_h, &pSrc->Integ4_SYSTEM_ENABLE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_ni);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_ni, &pSrc->Integ4_SYSTEM_ENABLE_ni, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_hx);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_hx, &pSrc->Integ4_SYSTEM_ENABLE_hx, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_ju);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_ju, &pSrc->Integ4_SYSTEM_ENABLE_ju, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_g);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_g, &pSrc->Integ4_SYSTEM_ENABLE_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_nf);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_nf, &pSrc->Integ4_SYSTEM_ENABLE_nf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_ma);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_ma, &pSrc->Integ4_SYSTEM_ENABLE_ma, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_bt);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_bt, &pSrc->Integ4_SYSTEM_ENABLE_bt, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_fm);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_fm, &pSrc->Integ4_SYSTEM_ENABLE_fm, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_ez);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_ez, &pSrc->Integ4_SYSTEM_ENABLE_ez, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_ls);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_ls, &pSrc->Integ4_SYSTEM_ENABLE_ls, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_f1);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_f1, &pSrc->Integ4_SYSTEM_ENABLE_f1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_jf);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_jf, &pSrc->Integ4_SYSTEM_ENABLE_jf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_el);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_el, &pSrc->Integ4_SYSTEM_ENABLE_el, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_k);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_k, &pSrc->Integ4_SYSTEM_ENABLE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_p);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_p, &pSrc->Integ4_SYSTEM_ENABLE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_kl);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_kl, &pSrc->Integ4_SYSTEM_ENABLE_kl, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_pg);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_pg, &pSrc->Integ4_SYSTEM_ENABLE_pg, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_ki);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_ki, &pSrc->Integ4_SYSTEM_ENABLE_ki, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_dn);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_dn, &pSrc->Integ4_SYSTEM_ENABLE_dn, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_ji);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_ji, &pSrc->Integ4_SYSTEM_ENABLE_ji, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_of);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_of, &pSrc->Integ4_SYSTEM_ENABLE_of, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_fz);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_fz, &pSrc->Integ4_SYSTEM_ENABLE_fz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_ob);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_ob, &pSrc->Integ4_SYSTEM_ENABLE_ob, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_fr);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_fr, &pSrc->Integ4_SYSTEM_ENABLE_fr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_gt);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_gt, &pSrc->Integ4_SYSTEM_ENABLE_gt, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_hxe);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_hxe, &pSrc->Integ4_SYSTEM_ENABLE_hxe, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_hj);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_hj, &pSrc->Integ4_SYSTEM_ENABLE_hj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_bk);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_bk, &pSrc->Integ4_SYSTEM_ENABLE_bk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_ph);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_ph, &pSrc->Integ4_SYSTEM_ENABLE_ph, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE);
   memcpy(&pDst->TrueRMS_MODE, &pSrc->TrueRMS_MODE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE);
   memcpy(&pDst->RMS_MODE, &pSrc->RMS_MODE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE_n);
   memcpy(&pDst->TrueRMS_MODE_n, &pSrc->TrueRMS_MODE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE_k);
   memcpy(&pDst->RMS_MODE_k, &pSrc->RMS_MODE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE_m);
   memcpy(&pDst->TrueRMS_MODE_m, &pSrc->TrueRMS_MODE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE_m);
   memcpy(&pDst->RMS_MODE_m, &pSrc->RMS_MODE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE_d);
   memcpy(&pDst->TrueRMS_MODE_d, &pSrc->TrueRMS_MODE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE_l);
   memcpy(&pDst->RMS_MODE_l, &pSrc->RMS_MODE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE_h);
   memcpy(&pDst->TrueRMS_MODE_h, &pSrc->TrueRMS_MODE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE_d);
   memcpy(&pDst->RMS_MODE_d, &pSrc->RMS_MODE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE_i);
   memcpy(&pDst->TrueRMS_MODE_i, &pSrc->TrueRMS_MODE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE_i);
   memcpy(&pDst->RMS_MODE_i, &pSrc->RMS_MODE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE_k);
   memcpy(&pDst->TrueRMS_MODE_k, &pSrc->TrueRMS_MODE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE_f);
   memcpy(&pDst->RMS_MODE_f, &pSrc->RMS_MODE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE_c);
   memcpy(&pDst->TrueRMS_MODE_c, &pSrc->TrueRMS_MODE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE_a);
   memcpy(&pDst->RMS_MODE_a, &pSrc->RMS_MODE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE_nz);
   memcpy(&pDst->TrueRMS_MODE_nz, &pSrc->TrueRMS_MODE_nz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE_o);
   memcpy(&pDst->RMS_MODE_o, &pSrc->RMS_MODE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE_ct);
   memcpy(&pDst->TrueRMS_MODE_ct, &pSrc->TrueRMS_MODE_ct, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE_b);
   memcpy(&pDst->RMS_MODE_b, &pSrc->RMS_MODE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE_ns);
   memcpy(&pDst->TrueRMS_MODE_ns, &pSrc->TrueRMS_MODE_ns, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE_a2);
   memcpy(&pDst->RMS_MODE_a2, &pSrc->RMS_MODE_a2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE_j);
   memcpy(&pDst->TrueRMS_MODE_j, &pSrc->TrueRMS_MODE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE_i4);
   memcpy(&pDst->RMS_MODE_i4, &pSrc->RMS_MODE_i4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE_nv);
   memcpy(&pDst->TrueRMS_MODE_nv, &pSrc->TrueRMS_MODE_nv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE_aw);
   memcpy(&pDst->RMS_MODE_aw, &pSrc->RMS_MODE_aw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystem1_fq);
   memcpy(&pDst->Subsystem1_fq, &pSrc->Subsystem1_fq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystempi2delay_f);
   memcpy(&pDst->Subsystempi2delay_f, &pSrc->Subsystempi2delay_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystem1_fd5);
   memcpy(&pDst->Subsystem1_fd5, &pSrc->Subsystem1_fd5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystempi2delay_b);
   memcpy(&pDst->Subsystempi2delay_b, &pSrc->Subsystempi2delay_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystem1_e);
   memcpy(&pDst->Subsystem1_e, &pSrc->Subsystem1_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystempi2delay_dm);
   memcpy(&pDst->Subsystempi2delay_dm, &pSrc->Subsystempi2delay_dm, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystem1_nk);
   memcpy(&pDst->Subsystem1_nk, &pSrc->Subsystem1_nk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystempi2delay_cs);
   memcpy(&pDst->Subsystempi2delay_cs, &pSrc->Subsystempi2delay_cs, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystem1_m);
   memcpy(&pDst->Subsystem1_m, &pSrc->Subsystem1_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystempi2delay_p);
   memcpy(&pDst->Subsystempi2delay_p, &pSrc->Subsystempi2delay_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystem1_fd);
   memcpy(&pDst->Subsystem1_fd, &pSrc->Subsystem1_fd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystempi2delay_l);
   memcpy(&pDst->Subsystempi2delay_l, &pSrc->Subsystempi2delay_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystem1_d);
   memcpy(&pDst->Subsystem1_d, &pSrc->Subsystem1_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystempi2delay_i);
   memcpy(&pDst->Subsystempi2delay_i, &pSrc->Subsystempi2delay_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystem1_j);
   memcpy(&pDst->Subsystem1_j, &pSrc->Subsystem1_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystempi2delay_e);
   memcpy(&pDst->Subsystempi2delay_e, &pSrc->Subsystempi2delay_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystem1_h);
   memcpy(&pDst->Subsystem1_h, &pSrc->Subsystem1_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystempi2delay_gm);
   memcpy(&pDst->Subsystempi2delay_gm, &pSrc->Subsystempi2delay_gm, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystem1_f);
   memcpy(&pDst->Subsystem1_f, &pSrc->Subsystem1_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystempi2delay_g);
   memcpy(&pDst->Subsystempi2delay_g, &pSrc->Subsystempi2delay_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->AutomaticGainControl_o);
   memcpy(&pDst->AutomaticGainControl_o, &pSrc->AutomaticGainControl_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystem1_k);
   memcpy(&pDst->Subsystem1_k, &pSrc->Subsystem1_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystempi2delay_d);
   memcpy(&pDst->Subsystempi2delay_d, &pSrc->Subsystempi2delay_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->AutomaticGainControl_j);
   memcpy(&pDst->AutomaticGainControl_j, &pSrc->AutomaticGainControl_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystem1_p);
   memcpy(&pDst->Subsystem1_p, &pSrc->Subsystem1_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Subsystempi2delay_n);
   memcpy(&pDst->Subsystempi2delay_n, &pSrc->Subsystempi2delay_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->AutomaticGainControl);
   memcpy(&pDst->AutomaticGainControl, &pSrc->AutomaticGainControl, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that sub-structures are copied in one operation since they cannot contain pointers.
 */
int OpalSnapshot_Copy_TimingData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int TimingSize = sizeof(tmpBuffer.Timing);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.Timing, src, TimingSize);

   eltSize = sizeof(pSrc->Timing.clockTick0);
   memcpy(&pDst->Timing.clockTick0, &pSrc->Timing.clockTick0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTick1);
   memcpy(&pDst->Timing.clockTick1, &pSrc->Timing.clockTick1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH0);
   memcpy(&pDst->Timing.clockTickH0, &pSrc->Timing.clockTickH0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH1);
   memcpy(&pDst->Timing.clockTickH1, &pSrc->Timing.clockTickH1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tFinal);
   memcpy(&pDst->Timing.tFinal, &pSrc->Timing.tFinal, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.firstInitCondFlag);
   memcpy(&pDst->Timing.firstInitCondFlag, &pSrc->Timing.firstInitCondFlag, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.offsetTimesArray);
   memcpy(&pDst->Timing.offsetTimesArray, &pSrc->Timing.offsetTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.perTaskSampleHitsArray);
   memcpy(&pDst->Timing.perTaskSampleHitsArray, &pSrc->Timing.perTaskSampleHitsArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleHitArray);
   memcpy(&pDst->Timing.sampleHitArray, &pSrc->Timing.sampleHitArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimesArray);
   memcpy(&pDst->Timing.sampleTimesArray, &pSrc->Timing.sampleTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimeTaskIDArray);
   memcpy(&pDst->Timing.sampleTimeTaskIDArray, &pSrc->Timing.sampleTimeTaskIDArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.simTimeStep);
   memcpy(&pDst->Timing.simTimeStep, &pSrc->Timing.simTimeStep, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tStart);
   memcpy(&pDst->Timing.tStart, &pSrc->Timing.tStart, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize);
   memcpy(&pDst->Timing.stepSize, &pSrc->Timing.stepSize, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize0);
   memcpy(&pDst->Timing.stepSize0, &pSrc->Timing.stepSize0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize1);
   memcpy(&pDst->Timing.stepSize1, &pSrc->Timing.stepSize1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stopRequestedFlag);
   memcpy(&pDst->Timing.stopRequestedFlag, &pSrc->Timing.stopRequestedFlag, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tArray);
   memcpy(&pDst->Timing.tArray, &pSrc->Timing.tArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.timeOfLastOutput);
   memcpy(&pDst->Timing.timeOfLastOutput, &pSrc->Timing.timeOfLastOutput, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that ingData must not be copied since it contains pointers.
 */
int OpalSnapshot_Copy_ModelData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int ModelDataSize = sizeof(tmpBuffer.ModelData);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.ModelData, src, ModelDataSize);

   eltSize = sizeof(pSrc->ModelData.CTOutputIncnstWithState);
   memcpy(&pDst->ModelData.CTOutputIncnstWithState, &pSrc->ModelData.CTOutputIncnstWithState, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.derivCacheNeedsReset);
   memcpy(&pDst->ModelData.derivCacheNeedsReset, &pSrc->ModelData.derivCacheNeedsReset, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.odeF);
   memcpy(&pDst->ModelData.odeF, &pSrc->ModelData.odeF, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.odeY);
   memcpy(&pDst->ModelData.odeY, &pSrc->ModelData.odeY, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.zCCacheNeedsReset);
   memcpy(&pDst->ModelData.zCCacheNeedsReset, &pSrc->ModelData.zCCacheNeedsReset, eltSize);
   size += eltSize;

   return size;
}

